---

env:
  global:
    - ANSIBLE_FORCE_COLOR: True
    - ANSIBLE_LOG_PATH: './ansible.log'
    - ANSIBLE_ROLES_PATH: '../'
  matrix:
    - distribution: 'centos'
      version: 7
      run_opts: '--privileged --volume="/sys/fs/cgroup:/sys/fs/cgroup:ro"'
    - distribution: 'ubuntu'
      version: 14.04
      run_opts: ''
    - distribution: 'ubuntu'
      version: 16.04
      run_opts: '--privileged --volume="/sys/fs/cgroup:/sys/fs/cgroup:ro"'

language: 'python'

python:
  - '2.7'

services:
  - 'docker'
  - 'rabbitmq'

sudo: 'required'


before_install:
  # Set up RabbitMQ user and permissions
  - 'sudo rabbitmqctl add_user test testpw'
  - 'sudo rabbitmqctl set_permissions test ".*" ".*" ".*"'

install:
  # Install test requirements
  - sudo apt-get update -qq
  - sudo apt-get install python-pip -y
  - sudo pip install ansible
  - sudo ansible-galaxy install -r tests/requirements.yml

before_script:
  # Build the container under test and run it.
  - >-
    docker build
    --file=tests/Dockerfile.${distribution}-${version}
    --tag=${distribution}-${version}
    tests

  - >-
    docker run
    --add-host=dockerhost:`/sbin/ip addr show docker0 | awk '/inet / {print $2}' | cut -d '/' -f1` --detach
    --env="ANSIBLE_LOG_PATH=/var/log/ansible.log"
    --detach
    --name="container"
    --volume=/etc/ansible/roles:/etc/ansible/roles:rw ${run_opts}
    --volume="${PWD}:/etc/ansible/roles/openstack-nova-compute:rw"
    ${run_opts} ${distribution}-${version}

script:
  # Check syntax of YAML files.
  - 'yamllint -c .yamllint.conf .'

  # Check syntax of role.
  - >-
    docker exec container ansible-playbook
    /etc/ansible/roles/openstack-nova-compute/tests/test_travis.yml --syntax-check

  # Run role.
  - >-
    docker exec container ansible-playbook
    /etc/ansible/roles/openstack-nova-compute/tests/test_travis.yml --diff --verbose


  # Run role again to check idempotence failure.
  - >-
    docker exec container ansible-playbook
    /etc/ansible/roles/openstack-nova-compute/tests/test_travis.yml --diff --verbose


  # Detect idempotence failure.
  - >-
    docker exec container
    tail -n 1 /var/log/ansible.log | grep -q "changed=0  *unreachable=0  *failed=0"

notifications:
  webhooks: 'https://galaxy.ansible.com/api/v1/notifications/'
