---

- name: Set service facts
  set_fact:
    nova_compute_service: nova-compute
  when: ansible_os_family == 'Debian'

- name: Set service facts
  set_fact:
    nova_compute_service: openstack-nova-compute
  when: ansible_os_family == 'RedHat'
