---

- name: Add tun device ACL to qemu.conf
  blockinfile:
    dest: '/etc/libvirt/qemu.conf'
    backup: True
    block: |
      cgroup_device_acl = [
          "/dev/null", "/dev/full", "/dev/zero",
          "/dev/random", "/dev/urandom",
          "/dev/ptmx", "/dev/kvm", "/dev/kqemu",
          "/dev/rtc","/dev/hpet", "/dev/vfio/vfio",
          "/dev/net/tun"
      ]

- name: Create selinux custom policy path
  file:
    path: '{{ openstack_nova_compute_selinux_policy_dir }}'
    state: directory
    owner: root
    group: root
    mode: 0750
  when: ansible_os_family == 'RedHat'

- name: Copy custom selinux policy
  copy:
    src: qemu-kvm-tun.te
    dest: '{{ openstack_nova_compute_selinux_policy_dir }}/qemu-kvm-tun.te'
    register: custom_policy_output
  when: ansible_os_family == 'RedHat'

- name: Load custom selinux policy
  command: /usr/sbin/semodule -u {{ openstack_nova_compute_selinux_policy_dir }}/qemu-kvm-tun.te
  when:
    - ansible_os_family == 'RedHat'
    - custom_policy_output.changed
